name: TigerClaim
version: 1.4.2
author: Bergtiger
main: de.bergtiger.claim.Claims
api-version: 1.16
description: Easy to Claim Regions.
depend: [WorldGuard]

commands:
  claim:
    aliases: [tclaim]
    description: creates a new Claim