main: de.bergtiger.claim.Claims
name: TigerClaim
version: ${minecraft.plugin.version}
author: Bergtiger
api-version: 1.16
description: Easy to Claim Regions.
depend: [WorldGuard]

commands:
  claim:
    aliases: [tclaim]
    description: creates a new Claim